version: "3"

services:
  estimate:
    container_name: estimate
    build: .
    ports:
      - 5000:5000
    networks:
      - dockeriseevsetup_asset_network

networks:
  dockeriseevsetup_asset_network:
    external: true


